version: 2
updates:
  - package-ecosystem: "npm" # specify npm as the package ecosystem
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: 'dev'
  - package-ecosystem: "github-actions" # specify GitHub Actions as the package ecosystem
    directory: "/.github/workflows" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: 'dev'
